[[plugins]]
repo = 'mattn/emmet-vim'
on_event = ['InsertEnter']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_post_source = '''
nnoremap <silent> <Space>rr :<C-u> T cargo run . <CR>
nnoremap <silent> <Space>rt :<C-u> T cargo test <CR>
'''

[[plugins]]
repo = 'pantharshit00/vim-prisma'
on_ft = ['prisma']

