return {
  -- 'pmizio/typescript-tools.nvim',
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   'neovim/nvim-lspconfig',
  -- },
  -- opts = {
  --   settings = {
  --     -- Example: Enable inlay hints
  --     inlayHints = {
  --       includeInlayParameterNameHints = 'all',
  --       includeInlayParameterNameHintsWhenArgumentMatchesName = false,
  --       includeInlayFunctionParameterTypeHints = true,
  --       includeInlayVariableTypeHints = true,
  --       includeInlayPropertyDeclarationTypeHints = true,
  --       includeInlayFunctionLikeReturnTypeHints = true,
  --       includeInlayEnumMemberValueHints = true,
  --     },
  --     tsserver_file_preferences = {
  --       includeInlayParameterNameHints = 'all',
  --       includeCompletionsForModuleExports = true,
  --     },
  --     jsx_close_tag = {
  --       enable = true,
  --       filetypes = { 'javascriptreact', 'typescriptreact' },
  --     },
  --     separate_diagnostic_server = true,
  --     publish_diagnostic_on = 'insert_leave',
  --   },
  -- },
}
